name: Lint and Test Terraform

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "testing"
          aws-secret-access-key: "testing" 

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Run Terraform fmt
        run: terraform fmt -check

      - name: Run Terraform Init 
        run: terraform -chdir=tests/ init

      - name: Run Terraform Plan on tests
        run: terraform -chdir=tests/ plan

      - name: Run Terraform Apply on tests
        run: terraform -chdir=tests/ apply

      - name: Run Terraform Destroy on tests
        run: terraform -chdir=tests/ destroy



