name: Lint and Test Terraform

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-west-2
      KUBECTL_VERSION: 1.21.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install RobotFramework
        run: pip install robotframework

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          kubectl_version:  v1.21.10

      - name: Run Terraform fmt
        run: terraform fmt -check

      - name: Run Terraform Init 
        run: terraform -chdir=tests/ init

      - name: Run Terraform Plan on tests
        run: terraform -chdir=tests/ plan

      - name: Run Terraform Apply on tests
        run: terraform -chdir=tests/ apply -auto-approve

      - name: Run RobotFramework Tests
        run: robot -i istio -e prerelease robot_tests/

      - name: Run Terraform Destroy on tests
        run: terraform -chdir=tests/ destroy -auto-approve



